import {
    chatbubbleOutline,
    happyOutline,
    peopleOutline,
    barChartOutline,
} from "ionicons/icons";

export type AssessmentTestType = "input-list" | "single-choice";

export type InputQuestion = {
    id: number;
    question: string;
};

export type ChoiceQuestion = {
    id: number;
    category: string;
    icon: string;
    question: string;
    options: { id: string; text: string }[];
};

export type AssessmentSection = {
    id: number;
    title: string;
    description: string;
    icon: string;
    type: AssessmentTestType;
    questions: (InputQuestion | ChoiceQuestion)[];
};

export const assessmentData: AssessmentSection[] = [
    {
        id: 1,
        title: "Chestionar de evaluare inițială a abilității de comunicare",
        description: "Mai jos sunt prezentate douăsprezece situații în care ați putea avea nevoie să comunicați. Abilitățile oamenilor de a comunica eficient variază foarte mult, iar uneori aceeași persoană poate comunica mai competent într-o anumită situație decât în alta.\n\nVă rugăm să indicați cât de competent considerați că sunteți în comunicare pentru fiecare dintre situațiile descrise mai jos. Notați în spațiul din stânga fiecărui item estimarea dumneavoastră privind nivelul de competență în comunicare.",
        icon: barChartOutline,
        type: "input-list",
        questions: [
            { id: 101, question: "Susțineți o prezentare în fața unui grup de persoane necunoscute" },
            { id: 102, question: "Vorbiți cu o cunoștință." },
            { id: 103, question: "Vorbiți într-o întâlnire mare cu prieteni." },
            { id: 104, question: "Vorbiți într-un grup mic de persoane necunoscute." },
            { id: 105, question: "Vorbiți cu un prieten." },
            { id: 106, question: "Vorbiți într-o întâlnire mare cu cunoștințe." },
            { id: 107, question: "Vorbiți cu o persoană necunoscută" },
            { id: 108, question: "Susțineți o prezentare în fața unui grup de prieteni" },
            { id: 109, question: "Vorbiți într-un grup mic de cunoștințe" },
            { id: 110, question: "Vorbiți într-o întâlnire mare cu persoane necunoscute" },
            { id: 111, question: "Vorbiți într-un grup mic de prieteni" },
            { id: 112, question: "Susțineți o prezentare în fața unui grup de cunoștințe" }
        ],
    },
    {
        id: 2,
        title: "Career Adapt-Abilities Inventory",
        description: "Oamenii folosesc diferite puncte forte pentru a-și construi cariera. Nimeni nu este bun la toate, iar fiecare persoană își dezvoltă anumite abilități mai mult decât altele. Te rugăm să evaluezi cât de dezvoltate sunt pentru tine următoarele abilități, utilizând scala de mai jos.\n\n5 = Foarte puternic dezvoltat\n4 = Puternic dezvoltat\n3 = Destul de dezvoltat\n2 = Puțin dezvoltat\n1 = Deloc dezvoltat",
        icon: chatbubbleOutline,
        type: "single-choice",
        questions: [
            {
                id: 201,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Mă gândesc cum va arăta viitorul meu.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
                {
                id: 202,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Îmi dau seama că alegerile de astăzi îmi influențează viitorul.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 203,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Mă pregătesc pentru viitor.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 204,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Devin conștient(ă) de alegerile educaționale și profesionale pe care trebuie să le fac.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 205,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Îmi planific modul în care îmi voi atinge obiectivele.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 206,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Sunt preocupat(ă) de cariera mea.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 207,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Încerc să rămân optimist(ă).",
                options: [
                    {   id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 208,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Iau decizii pe cont propriu.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 209,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Îmi asum responsabilitatea pentru acțiunile mele.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 210,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Îmi susțin convingerile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 211,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Mă bazez pe mine însumi/însămi.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 212,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Fac ceea ce consider că este potrivit pentru mine.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 213,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Explorez mediul din jurul meu.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 214,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Caut oportunități de dezvoltare personală.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 215,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Analizez opțiunile înainte de a lua o decizie.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 216,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Observ diferite moduri de a face lucrurile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 217,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Analizez în profunzime întrebările pe care le am.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 218,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Devin curios/curioasă cu privire la noi oportunități.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 219,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Îndeplinesc sarcinile eficient.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 220,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Am grijă să fac lucrurile bine.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 221,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Învăț abilități noi.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 222,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Muncesc la capacitatea mea maximă.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 223,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Depășesc obstacolele.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 224,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "Rezolv problemele eficient.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
        ],
    },
    {
        id: 3,
        title: "Emotional Intelligence Assessment",
        description: "Te rugăm să evaluezi cât de dezvoltate sunt pentru tine următoarele abilități, utilizând scala de mai jos.\n\n5 = Foarte puternic dezvoltat\n4 = Puternic dezvoltat\n3 = Destul de dezvoltat\n2 = Puțin dezvoltat\n1 = Deloc dezvoltat",
        icon: happyOutline,
        type: "single-choice",
        questions: [
            {
                id: 301,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Recunosc foarte bine emoția pe care o simte o persoană în orice moment dat.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
                {
                id: 302,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Chiar și atunci când sunt foarte nervos/nervoasă, știu ce să urmăresc pentru a înțelege emoțiile celorlalți.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 303,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Pot întotdeauna să sesizez schimbările din starea emoțională a unei persoane.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             {
                id: 304,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi este ușor să descriu emoțiile pe care le simte o persoană.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 305,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Anticipez întotdeauna corect comportamentul unei persoane pe baza emoțiilor pe care aceasta le simte.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 306,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Înțeleg întotdeauna cum o emoție poate genera o alta.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 307,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Sunt capabil(ă) să prezic corect ce voi face pe baza emoției pe care o simt.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 308,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi descriu emoțiile foarte ușor.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 309,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Sunt conștient(ă) de emoțiile mele în fiecare moment.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 310,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Sunt conștient(ă) de emoțiile mele chiar și în situații dificile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 311,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi dau seama rapid ce anume îmi generează emoțiile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 312,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi este ușor să înțeleg factorii care îmi influențează emoțiile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 313,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Sunt întotdeauna capabil(ă) să liniștesc pe cineva, dacă este nevoie.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 314,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îi ajut adesea pe ceilalți să depășească stări emoționale dificile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 315,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Dacă o cunoștință este tristă, sunt capabil(ă) să o fac să se simtă mai bine.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 316,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Întotdeauna țin cont de emoțiile mele atunci când iau o decizie.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 317,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Pot simula diverse emoții dacă este nevoie.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 318,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi exprim emoțiile spontan pentru a obține efectul dorit.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 319,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi pot folosi emoțiile pentru a atinge un scop.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 320,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Sunt capabil(ă) să îmi temperez bine izbucnirile emoționale.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 321,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "De obicei, îmi depășesc singur(ă) stările emoționale neplăcute.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 322,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Emoțiile mele nu mă împiedică să îmi desfășor activitățile.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 323,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Întotdeauna îmi folosesc emoțiile atunci când comunic.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
            {
                id: 324,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "Îmi dau seama rapid care sunt posibilele consecințe (fiziologice sau comportamentale) ale emoțiilor mele.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            },
             
        ],
    },
    {
        id: 4,
        title: "Teamwork Assessment",
        description: "Te rugăm să evaluezi cât de dezvoltate sunt pentru tine următoarele abilități, utilizând scala de mai jos.\n\n5 = Foarte puternic dezvoltat\n4 = Puternic dezvoltat\n3 = Destul de dezvoltat\n2 = Puțin dezvoltat\n1 = Deloc dezvoltat",
        icon: peopleOutline,
        type: "single-choice",
        questions: [
            {
                id: 401,
                category: "Teamwork",
                icon: peopleOutline,
                question: "Prefer să lucrez mai degrabă în sarcini de echipă decât în sarcini individuale.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
             },
             {
                id: 402,
                category: "Teamwork",
                icon: peopleOutline,
                question: "Când am de ales, încerc să lucrez în grup în loc de unul singur.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
             },
             {
                id: 403,
                category: "Teamwork",
                icon: peopleOutline,
                question: "Mie, personal, îmi face plăcere să lucrez cu alţii.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
             },
             {
                id: 404,
                category: "Teamwork",
                icon: peopleOutline,
                question: "Lucrul în grup este mai bun decât lucrul de unul singur.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
             },
             {
                id: 405,
                category: "Teamwork",
                icon: peopleOutline,
                question: "A lucra în grup este mai bine decât a lucra singur.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
             },
             {
                id: 406,
                category: "Teamwork",
                icon: peopleOutline,
                question: "Dacă aş avea de ales, aş realiza mai degrabă o sarcină în care pot lucra de unul singur decât să realizez o sarcină în care trebuie să muncesc cu alţii în grup.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
             },
             {
                id: 407,
                category: "Teamwork",
                icon: peopleOutline,
                question: "Îmi place să interacţionez cu alţii atunci când lucrez la proiecte.",
                options: [
                    { id: "1", text: "Deloc dezvoltat" },
                    { id: "2", text: "Puțin dezvoltat" },
                    { id: "3", text: "Destul de dezvoltat" },
                    { id: "4", text: "Puternic dezvoltat" },
                    { id: "5", text: "Foarte puternic dezvoltat" },
                ],
            }
        ],
    },
];
