import {
    chatbubbleOutline,
    happyOutline,
    peopleOutline,
    barChartOutline,
} from "ionicons/icons";

export type AssessmentTestType = "input-list" | "single-choice";

export type InputQuestion = {
    id: number;
    question: string;
};

export type ChoiceQuestion = {
    id: number;
    category: string;
    icon: string;
    question: string;
    options: { id: string; text: string }[];
};

export type AssessmentSection = {
    id: number;
    title: string;
    description: string;
    icon: string;
    type: AssessmentTestType;
    questions: (InputQuestion | ChoiceQuestion)[];
};

export const assessmentData: AssessmentSection[] = [
    {
        id: 1,
        title: "initialAssessment.sections.1.title",
        description: "initialAssessment.sections.1.description",
        icon: barChartOutline,
        type: "input-list",
        questions: [
            { id: 101, question: "initialAssessment.sections.1.questions.101" },
            { id: 102, question: "initialAssessment.sections.1.questions.102" },
            { id: 103, question: "initialAssessment.sections.1.questions.103" },
            { id: 104, question: "initialAssessment.sections.1.questions.104" },
            { id: 105, question: "initialAssessment.sections.1.questions.105" },
            { id: 106, question: "initialAssessment.sections.1.questions.106" },
            { id: 107, question: "initialAssessment.sections.1.questions.107" },
            { id: 108, question: "initialAssessment.sections.1.questions.108" },
            { id: 109, question: "initialAssessment.sections.1.questions.109" },
            { id: 110, question: "initialAssessment.sections.1.questions.110" },
            { id: 111, question: "initialAssessment.sections.1.questions.111" },
            { id: 112, question: "initialAssessment.sections.1.questions.112" }
        ],
    },
    {
        id: 2,
        title: "initialAssessment.sections.2.title",
        description: "initialAssessment.sections.2.description",
        icon: chatbubbleOutline,
        type: "single-choice",
        questions: [
            {
                id: 201,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.201",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 202,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.202",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 203,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.203",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 204,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.204",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 205,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.205",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 206,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.206",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 207,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.207",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 208,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.208",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 209,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.209",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 210,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.210",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 211,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.211",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 212,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.212",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 213,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.213",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 214,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.214",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 215,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.215",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 216,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.216",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 217,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.217",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 218,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.218",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 219,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.219",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 220,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.220",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 221,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.221",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 222,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.222",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 223,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.223",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 224,
                category: "Adaptability",
                icon: chatbubbleOutline,
                question: "initialAssessment.sections.2.questions.224",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
        ],
    },
    {
        id: 3,
        title: "initialAssessment.sections.3.title",
        description: "initialAssessment.sections.3.description",
        icon: happyOutline,
        type: "single-choice",
        questions: [
            {
                id: 301,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.301",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
                {
                id: 302,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.302",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 303,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.303",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             {
                id: 304,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.304",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 305,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.305",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 306,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.306",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 307,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.307",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 308,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.308",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 309,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.309",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 310,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.310",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 311,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.311",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 312,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.312",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 313,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.313",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 314,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.314",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 315,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.315",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 316,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.316",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 317,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.317",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 318,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.318",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 319,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.319",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 320,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.320",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 321,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.321",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 322,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.322",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 323,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.323",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
            {
                id: 324,
                category: "Emotional intelligence",
                icon: happyOutline,
                question: "initialAssessment.sections.3.questions.324",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            },
             
        ],
    },
    {
        id: 4,
        title: "initialAssessment.sections.4.title",
        description: "initialAssessment.sections.4.description",
        icon: peopleOutline,
        type: "single-choice",
        questions: [
            {
                id: 401,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.401",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
             },
             {
                id: 402,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.402",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
             },
             {
                id: 403,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.403",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
             },
             {
                id: 404,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.404",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
             },
             {
                id: 405,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.405",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
             },
             {
                id: 406,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.406",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
             },
             {
                id: 407,
                category: "Teamwork",
                icon: peopleOutline,
                question: "initialAssessment.sections.4.questions.407",
                options: [
                    { id: "1", text: "initialAssessment.options.1" },
                    { id: "2", text: "initialAssessment.options.2" },
                    { id: "3", text: "initialAssessment.options.3" },
                    { id: "4", text: "initialAssessment.options.4" },
                    { id: "5", text: "initialAssessment.options.5" },
                ],
            }
        ],
    },
];
